### ISSUE TITLE
Is it possible to add a Logo 

### ISSUE THREAD

**Issue by planetahuevo** [InterNations/antwort#29]
Hi, 
I just found this antwort and is great. Thanks!

I was wondering, is it possible to add a Logo that replace the title? 

Also I found missing a place to locate a "Open on the web" link. I know it shouldn´t be necesary to use it if the responsive is working, but you now, some people like to do it. 

Thanks!

**Comment by jng5** [comment]
Both those are just simple use cases that don't involve any tricky HTML. So I don't I think I need to illustrate that…

If you're looking for inspiration in terms of how to place them, there are various examples on the web.

**Comment by planetahuevo** [comment]
Well, the problem is to make a logo that does not break the responsive. So the "web" can help me with the html but not with its implication on this templates. 
I will try some options myself then. 
Thank you!

**Comment by jng5** [comment]
An image cannot "break the responsive". If you need a logo, make sure the `<img>` has `width` and `height` attributes. Then just add `max-width: 100%` and you will be fine in most cases.

**Comment by planetahuevo** [comment]
Thank you for the tips! I think I was able to insert the logo an so far it looks good. 

The max-width:100% is the important part here.
