### ISSUE TITLE
Duplicate attribute and styles

### ISSUE THREAD

**Issue by rjmiddleton** [InterNations/antwort#32]
Thanks for a great resource!

Wondering what is the reason for adding styles that match the tag attributes, e.g.

\<table border="0" width="600" cellpadding="0" cellspacing="0" class="container" style="width:600px;max-width:600px"\>

(width is specified as an attribute and a style)

Is the duplication deliberate here? If so, could you help me understand why?

Thanks,
Russell

**Comment by michaelrimbach** [comment]
Because some mail clients ignores the style tag (and others).

**Comment by jng5** [comment]
Someone will have to correct me if I am wrong, but I think…

The Gmail App on Android fudges it's own responsive version, adjusting your table widths, etc. to fit to the screen width. At some point I got in the habit of redundantly defining widths in pixels too.

It doesn't hurt so I've left it in. But at some point I do need to review if it's necessary.
