### ISSUE TITLE
Yahoo App doesn't support Multiple Selectors

### ISSUE THREAD

**Issue by RequestingMark** [InterNations/antwort#33]
I was testing out antwort and I came across an issue in the Yahoo Mail App where the force-rows were not going 100% width. 

It seems as though the yahoo mail app does not support multiple selectors and I was able to fix the issue by changing this:

```
@media screen and (max-width: 599px) {
  table[class="force-row"],
  table[class="container"] {
    width: 100% !important;
    max-width: 100% !important;
  }
}
```

to this

```
@media screen and (max-width: 599px) {
  table[class="force-row"] {
    width: 100% !important;
    max-width: 100% !important;
  }
  table[class="container"] {
    width: 100% !important;
    max-width: 100% !important;
  }
}
```

**Comment by jng5** [comment]
Hi Mark, do you mean the Yahoo App on iOS? I want to see if I can reproduce the problem…

Btw, it's possible to remove the attribute CSS selector syntax now that [Yahoo Mail supports media queries](https://www.emailonacid.com/blog/article/industry-news/yahoo_mail_now_supports_media_queries). Good reminder for me to update the template ;)

**Comment by RequestingMark** [comment]
I was testing using Android (Samsung Galaxy S5).

**Comment by barayuda** [comment]
Thanks, this help me.
It's work :)

**Comment by jng5** [comment]
Since [Yahoo fixed their media query bug](http://freshinbox.com/blog/yahoo-mail-fixes-media-query-bug-yahoo/), this should hopefully not be an issue anymore.
