### ISSUE TITLE
build.html doesn't include style.css

### ISSUE THREAD

**Issue by postme** [InterNations/antwort#34]
Hi, first of thank you for putting this on Github, I love the simplicity and the robustness of the templates.

The title says it all, it looks like during the build of build.html the style.css content isnt included. I checked all 3 templates and neither one contain the style.css content.

**Comment by kylepfeeley** [comment]
CSS styling is inline and also in the `<style>` tag in the `<head>` of the html files.

**Comment by postme** [comment]
Check the build.html files, the content of style.css isn't included in the <head>, unless I'm getting very cross eyed at the end of the day :-)

**Comment by kylepfeeley** [comment]
Correct, there is not a css file, all the styles in emails html files are inline, not in a stylesheet. For example:

```<body style="margin:0; padding:0;" bgcolor="#F0F0F0" leftmargin="0" topmargin="0" marginwidth="0" marginheight="0">```

The style attribute is `margin:0; padding:0;` and the there is also styling applied by specific style attributes like bgcolor: `bgcolor="#F0F0F0"`

There is also some styling in the head in a `<style>` tag, but that gets stripped by many non-mobile email clients.

**Comment by postme** [comment]
Ok, if I understand correctly the contents of style.css gets mapped to the equivalent class in the html file? i.e. in styles.css the .container content is mapped to the element containing class="container" and then written out as an inline style attribute, correct?
