### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by tordans** [InterNations/antwort#35]
Those links are broken, they show https://litmus.com/unavailable
- https://litmus.com/pub/de912ba
- https://litmus.com/pub/23497a4
- https://litmus.com/pub/2e0aaa0

> 404
> The test results you’re looking for cannot be found
> This link may be out of date, expired, or removed by the person who originally shared it.
> Litmus is a leading email testing and analytics tool. Check out the homepage for more details."

**Comment by saibotsivad** [comment]
Same here. I was hoping to look at the demos, sad story.

**Comment by jng5** [comment]
Sorry about that. It looks like Litmus expired the links at some point. I just regenerated them. 

**Please excuse the broken Litmus thumbnails**, which have the white container background missing in many cases. I've verified by hand that the template works as intended. And if you click on Litmus' larger version, it is fine. I've been told the thumbnail generator may be taking screenshots prematurely…

- **Single Column**
  https://litmus.com/pub/f6f088c

- **Two Columns**
  https://litmus.com/pub/884c2a3

- **Three Columns**
  https://litmus.com/pub/eae4ebf

**Comment by saibotsivad** [comment]
Awesome, thanks!
