### ISSUE TITLE
Single column image

### ISSUE THREAD

**Issue by federicovilla** [InterNations/antwort#39]
Hallo, thanks for sharing these great templates.
I'm wondering how the singel column template could use responsive image, just a bigger image on top or in the middle of the main email body.
Thanks

**Comment by jng5** [comment]
@federicovilla 

You can add an image anywhere. Just remember to inline `max-width:100%` on the image, for example:

```
<img src="image.png" border="0" width="500" height="100" hspace="0" vspace="0" style="max-width:100%;">
```
Cheers
Julie
